FROM docker.io/grafana/grafana:latest

COPY datasources.yaml /etc/grafana/provisioning/datasources/datasources.yaml
COPY dashboards.yaml /etc/grafana/provisioning/dashboards/dashboards.yaml
COPY dashboards /etc/dashboards
