{
 "title": "VPN Connectivity",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "15s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Per-Site Median Ping Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gondor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(.5, probe_duration_seconds{job=\"vpn_icmp\", instance=\"192.168.0.1\"}[$interval])"
    }
   ]
  },
  {
   "title": "Rindge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(.5, probe_duration_seconds{job=\"vpn_icmp\", instance=\"192.168.1.1\"}[$interval])"
    }
   ]
  },
  {
   "title": "VPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(.5, probe_duration_seconds{job=\"vpn_icmp\", instance=\"192.168.8.1\"}[$interval])"
    }
   ]
  },
  {
   "title": "Chateau",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(.5, probe_duration_seconds{job=\"vpn_icmp\", instance=\"184.56.215.10\"}[$interval])"
    }
   ]
  },
  { "title": "Overall Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Global Median Ping Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(.5, probe_duration_seconds{job=\"vpn_icmp\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Global Slow Probe Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(quantile_over_time(.5, probe_duration_seconds{job=\"vpn_icmp\"}[$interval]) >=1 )"
    }
   ]
  }
 ]
}